<?php

/**
 * @file
 * Make the login screens better :).
 */

/**
 * Implements hook_form_alter().
 *
 * Autofocus on the username field.
 * Some proper page titles would be nice for a change,
 * User account is a bit boring..
 */
function betterlogin_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Autofocus on the username field.
  // And add some pretty CSS :).
  // And a few other things too...
  if ($form_id == 'user_login_form' || $form_id == 'user_register_form' || $form_id == 'user_pass' || $form_id == 'user_pass_reset') {
    $form['name']['#attributes']['autofocus'] = 'autofocus';
    // We don't really need descriptions to tell us what we already know...
    unset($form['name']['#description']);
    unset($form['pass']['#description']);
    unset($form['user_picture']);

    // Add in some CSS.
    $form['#attached']['library'][] = 'betterlogin/betterlogin_css';
  }

  // Exit if we're not on a target url, since the form may have been rendered
  // programmatically. We don't want to change page titles on other pages.
  $pages = array('login', 'register', 'password', 'reset');
  // Retrieve an array which contains the path pieces.
  $current_path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $current_path);
  if (!in_array($path_args, $pages)) {
    return;
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function betterlogin_theme_registry_alter(&$theme_registry) {
  $pages = [
    'page__user__login' => 'page--user--login',
    'page__user__register' => 'page--user--register',
    'page__user__password' => 'page--user--password',
    'page__user__reset' => 'page--user--reset',
  ];
  $mod_path = drupal_get_path('module', 'betterlogin') . '/templates';

  foreach ($pages as $key => $template) {
    $theme_registry[$key]['template'] = $template;
    $theme_registry[$key]['path'] = $mod_path;
    $theme_registry[$key]['preprocess functions'][0] = 'betterlogin_preprocess_page';
    $theme_registry[$key]['preprocess functions'][1] = 'betterlogin_preprocess_html';
  }
}

/**
 * Implements hook_preprocess_page().
 */
function betterlogin_preprocess_page(&$variables) {
  $variables['site_name'] = \Drupal::config('system.site')->get('name');
  $variables['logo'] = '/core/themes/bartik/logo.svg';
  $current_path = \Drupal::service('path.current')->getPath();
  switch ($current_path) {
    case '/user/login':
      $variables['title'] = t('Login');
      break;

    case '/user/password':
      $variables['title'] = t('Forgot your password?');
      break;

    case '/user/register':
      $variables['title'] = t('Register');
      break;

    case '/user/reset':
      $variables['title'] = t('Reset password');
      break;
  }

  $variables['#cache']['contexts'][] = 'route';
  $variables['page']['#cache']['contexts'][] = 'route';
  $variables['page']['content']['bartik_local_tasks'] = array();
  $variables['page']['content']['bartik_page_title'] = array();
}

/**
 * Implements hook_preprocess_html();
 */
function betterlogin_preprocess_html(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  switch ($current_path) {
    case '/user/login':
      $variables['head_title']['title'] = t('Login');
      break;

    case '/user/password':
      $variables['head_title']['title'] = t('Forgot your password?');
      break;

    case '/user/register':
      $variables['head_title']['title'] = t('Register');
      break;

    case '/user/reset':
      $variables['head_title']['title'] = t('Reset password');
      break;
  }

  $variables['#cache']['contexts'][] = 'route';
  $variables['page']['#cache']['contexts'][] = 'route';
}
